### ISSUE TITLE
Criação dos RestControllers (Classe de recursos)de consumo endpoint para. Listagem ID e Serviço(PR1)

### ISSUE THREAD

**Issue by IaraBeco** [IaraBeco/helpr#1]

**Comment by soulcode-acad** [comment]
Oba Iara trabalho legal demais, obrigado pela evolução alguns trechos ficaram sem autoria pode ser que precise de mais atenção principalmente nas notações e nomenclaturas de projeto, alguns objetos podem dar erro com os nomes utilizados. De resto estava tudo legal faltou etiquetar para ajudar quem faz qualidade e revisão do código e algumas funções deram falhas. Mas ótimo trabalho minha amiga vamos tentar fechar e certificar okay!

![image](https://user-images.githubusercontent.com/100297907/173601312-8f3f8c32-72d2-4229-8fad-298dca23a99a.png)
